#!/usr/bin/env python3
"""Generate encrypted_frag_*.cpp from secrets.
   Split the 243-byte encrypted blob into 5 scrambled fragments.
   Matches the BlobAssembler in relay_crypto.cpp."""

import os, random, sys
try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("Error: need 'pip install cryptography'")
    sys.exit(1)

# ── Same secrets as before ──
SECRETS = [
    (b"tcp://8.218.97.97:11010", "Relay"),
    (b"8.218.",                  "Relay"),
    (b"https://beta-auth-scllhxgtcn.cn-shenzhen.fcapp.run", "Worker"),
]

def hexdump(data):
    return ", ".join(f"0x{b:02x}" for b in data)

def build_encrypted_blob(secrets):
    """Encrypt secrets, build 243-byte flat blob."""
    keys = {}
    salts = {}
    entries_by_ns = {}
    for plaintext, ns in secrets:
        if ns not in keys:
            keys[ns] = AESGCM.generate_key(256)
            salts[ns] = os.urandom(8)
            entries_by_ns[ns] = []
        entries_by_ns[ns].append(plaintext)

    encrypted = {}
    for ns, plaintexts in entries_by_ns.items():
        key = keys[ns]
        salt = salts[ns]
        final_key = bytes(a ^ b for a, b in zip(key, salt * 4))
        encrypted[ns] = []
        for plaintext in plaintexts:
            nonce = os.urandom(12)
            aes = AESGCM(final_key)
            ct_with_tag = aes.encrypt(nonce, plaintext, None)
            tag = ct_with_tag[-16:]
            ct = ct_with_tag[:-16]
            encrypted[ns].append((nonce, ct, tag))

    r_salt, r_key = salts["Relay"], keys["Relay"]
    r_nonce1, r_ct1, r_tag1 = encrypted["Relay"][0]
    r_nonce2, r_ct2, r_tag2 = encrypted["Relay"][1]
    w_salt, w_key = salts["Worker"], keys["Worker"]
    w_nonce, w_ct, w_tag = encrypted["Worker"][0]

    blob_parts = [
        r_salt, r_key, r_nonce1, r_ct1, r_tag1,
        r_nonce2, r_ct2, r_tag2,
        w_salt, w_key, w_nonce, w_ct, w_tag,
    ]
    return b"".join(blob_parts)

def split_blob(blob):
    """Split 243-byte blob into 5 fragments: 49,49,49,48,48."""
    assert len(blob) == 243
    sizes = [49, 49, 49, 48, 48]
    frags = []
    off = 0
    for s in sizes:
        frags.append(blob[off:off+s])
        off += s
    return frags

def scramble(segment):
    """Given a segment of the blob, generate random permutation and scrambled data.
    restore(d, p, cnt): output[off + p[i]] = d[i]
    So d[i] = segment[p[i]]  (place byte at position p[i] into output[i])
    """
    n = len(segment)
    perm = list(range(n))
    random.shuffle(perm)
    # d[i] = segment[perm[i]]
    data = bytearray(n)
    for i in range(n):
        data[i] = segment[perm[i]]
    return bytes(data), bytes(perm)

def write_frag_cpp(index, data, perm, out_dir):
    n = len(data)
    filename = f"encrypted_frag_{index+1}.cpp"
    path = os.path.join(out_dir, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by generate_fragments.py\n")
        f.write(f"// Scrambled fragment {index+1}/5 ({n} bytes)\n")
        f.write(f'#include "encrypted_frag_{index+1}.h"\n\n')
        f.write(f"namespace Frag{index+1} {{\n")
        f.write(f"    const uint8_t data[{n}] = {{ {hexdump(data)} }};\n")
        f.write(f"    const uint8_t perm[{n}] = {{ {hexdump(perm)} }};\n")
        f.write("}\n")
    print(f"  Written: {filename}")

def main():
    # Determine output directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    proj_root = os.path.dirname(script_dir)  # D:\latest-code\cpp
    out_dir = os.path.join(proj_root, "src", "multiplayer")

    print("Encrypting secrets...")
    blob = build_encrypted_blob(SECRETS)
    print(f"  Blob: {len(blob)} bytes")

    frags = split_blob(blob)
    for i, frag in enumerate(frags):
        print(f"  Fragment {i+1}: {len(frag)} bytes")
        data, perm = scramble(frag)
        write_frag_cpp(i, data, perm, out_dir)

    print(f"\nDone. Place the 5 files in {out_dir}")
    print("CMakeLists.txt will auto-detect their presence.")

if __name__ == "__main__":
    main()
