// AUTO-GENERATED by tools/encrypt_addr.py — DO NOT EDIT
// Fragment-agnostic layout offsets (same for all compilations).
// Included by relay_crypto.cpp.
#pragma once
#include <cstddef>

constexpr size_t  kRelaySaltOff = 0;
constexpr size_t  kRelaySaltLen = 8;
constexpr size_t  kRelayKeyOff = 8;
constexpr size_t  kRelayKeyLen = 32;
constexpr size_t  kRelayNonceOff = 40;
constexpr size_t  kRelayNonceLen = 12;
constexpr size_t  kRelayCTOff = 52;
constexpr size_t  kRelayCTLen = 23;
constexpr size_t  kRelayTagOff = 75;
constexpr size_t  kRelayTagLen = 16;
constexpr size_t  kRelayPrefixNonceOff = 91;
constexpr size_t  kRelayPrefixNonceLen = 12;
constexpr size_t  kRelayPrefixCTOff = 103;
constexpr size_t  kRelayPrefixCTLen = 6;
constexpr size_t  kRelayPrefixTagOff = 109;
constexpr size_t  kRelayPrefixTagLen = 16;
constexpr size_t  kWorkerSaltOff = 125;
constexpr size_t  kWorkerSaltLen = 8;
constexpr size_t  kWorkerKeyOff = 133;
constexpr size_t  kWorkerKeyLen = 32;
constexpr size_t  kWorkerNonceOff = 165;
constexpr size_t  kWorkerNonceLen = 12;
constexpr size_t  kWorkerCTOff = 177;
constexpr size_t  kWorkerCTLen = 50;
constexpr size_t  kWorkerTagOff = 227;
constexpr size_t  kWorkerTagLen = 16;
