// AUTO-GENERATED by tools/encrypt_addr.py — Fragment 3/5
// Headers are safe to commit (extern const declarations only).
#pragma once
#include <cstdint>
#include <cstddef>

namespace Frag3 {
    // 49 permuted bytes (scrambled)
    extern const uint8_t data[49];
    // Inverse permutation: restore[perm[i]] = data[i]
    extern const uint8_t perm[49];
} // namespace Frag3
