// AUTO-GENERATED by tools/encrypt_addr.py — Fragment 4/5
// Headers are safe to commit (extern const declarations only).
#pragma once
#include <cstdint>
#include <cstddef>

namespace Frag4 {
    // 48 permuted bytes (scrambled)
    extern const uint8_t data[48];
    // Inverse permutation: restore[perm[i]] = data[i]
    extern const uint8_t perm[48];
} // namespace Frag4
